name: Assign random reviewers to PR

on:
  pull_request:
    types: [opened]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Randomly assign reviewers, excluding PR author
        uses: actions/github-script@v7
        with:
          script: |
            const reviewers = ['ZL-Asica', 'chipanyanwu', 'WeiViv', 'marycaserio', 'WelldoneM'];
            const prAuthor = context.payload.pull_request.user.login; // Get PR author

            // Filter out the PR author from the list of reviewers
            const availableReviewers = reviewers.filter(reviewer => reviewer !== prAuthor);

            // Shuffle the reviewers
            const shuffledReviewers = availableReviewers.sort(() => 0.5 - Math.random());
            const selectedReviewers = shuffledReviewers.slice(0, 2); // Select 2 reviewers

            // Assign the selected reviewers to the PR
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: selectedReviewers
            });
