name: size-label
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      sizeLabel: ${{ steps.size-label.outputs.sizeLabel }}
    steps:
      - name: size-label
        id: size-label
        uses: 'pascalgn/size-label-action@v0.5.4'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }
  comment:
    runs-on: ubuntu-latest
    needs: size-label
    if: ${{ contains(needs.size-label.outputs.sizeLabel, 'XL') }}
    steps:
      - run: echo "Too big PR"
